version: '1.0.{build}'
configuration:
- Debug
- Release
platform: Any CPU
environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
before_build:
- appveyor-retry dotnet restore -v Minimal
build_script:
- dotnet build "src\CommandPattern"
after_build:
- dotnet pack "src\CommandPattern"
- dotnet publish "src\CommandPattern"
test_script:
- dotnet test "test\CommandPatternTests"